CREATE TRIGGER `audit_user` BEFORE UPDATE ON `User` FOR EACH ROW IF OLD.EMAIL != NEW.EMAIL THEN
INSERT INTO History VALUES (UUID(), UTC_TIMESTAMP(), NEW.ID, CONCAT("User ", NEW.name," Mengganti Email"), NEW.EMAIL, OLD.EMAIL);
ELSEIF OLD.PHONE != NEW.PHONE THEN
INSERT INTO History VALUES (UUID(), UTC_TIMESTAMP(), NEW.ID, CONCAT("User ", NEW.name," Mengganti No.HP"), NEW.PHONE, OLD.PHONE);
END IF